# Generated by Django 3.2.9 on 2021-11-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduinos',
            name='Habitaciones',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Habitaciones',
        ),
        migrations.AddField(
            model_name='arduinos',
            name='Habitacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_arduinos', to='API.habitaciones'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Habitacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_reserva', to='API.habitaciones'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='Tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_habitacion_habitaciones', to='API.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_reserva', to='API.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
    ]
