# Generated by Django 3.2.9 on 2021-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211122_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='Cantidad_camas',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
