# Generated by Django 3.2.9 on 2021-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20211122_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinos',
            name='Temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
