# Generated by Django 3.2.9 on 2021-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_arduinos_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='Nro_habitacion',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='Estado_habitacion',
            field=models.CharField(choices=[('1', 'A'), ('2', 'X')], max_length=2),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='Wifi',
            field=models.CharField(choices=[('1', '4G'), ('2', '5G')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_inicio',
            field=models.DateField(),
        ),
    ]
